
development:
  debug: true


test: &test
  debug: true

cucumber:
  <<: *test

staging:
  debug: true

## final settings, but not yet
production:
  debug: false

all:
  tvdb_api_key: 630FCFC5489C56B0

  roots:
   tv: "/Volumes/fantom/Shared/media/tv"
   movies: "/Volumes/fantom/Shared/media/movies"
